name: Alerta Telegram

on:
  push:

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para o Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST \
            "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${TELEGRAM_CHAT_ID}\",\"text\":\"Novo commit no repositório DevOps. Autor: ${{ github.actor }} - Commit: ${{ github.event.head_commit.message }}\"}"
